ARG CUDA_VERSION=12.8.1

FROM nvcr.io/nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04 AS base

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Asia/Shanghai

WORKDIR /workspace

##############################################################################
# Install Basic Utilities
##############################################################################
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    echo "N" | apt-get install -y --no-install-recommends pkg-config && \
    apt-get install -y --no-install-recommends \
        autotools-dev \
        build-essential \
        ca-certificates ccache cmake curl \
        emacs \
        gcc git git-lfs g++ \
        htop \
        iftop iotop \
        libcairo2-dev libfontconfig-dev libibverbs1 libibverbs-dev libnuma-dev libx11-dev lsb-release \
        net-tools nfs-common ninja-build \
        openssh-server openssh-client \
        pdsh psmisc \
        rsync \
        screen software-properties-common sudo \
        tmux tzdata \
        unzip \
        vim \
        wget

##############################################################################
# Install Python and essential tools
##############################################################################
ARG PYTHON_VERSION=3.12
RUN set -eux && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update -y  && \
    apt-get install -y --no-install-recommends \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-venv \
        python3-distutils \
        python3-pip && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 && \
    update-alternatives --set python3 /usr/bin/python${PYTHON_VERSION} && \
    ln -sf /usr/bin/python${PYTHON_VERSION}-config /usr/bin/python3-config && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    python -m ensurepip --upgrade && \
    python -m pip install --upgrade setuptools && \
    # Cleanup
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Remove legacy blinker if present
    rm -rf /usr/lib/python3/dist-packages/blinker*

##############################################################################
# Install sccache from official release
##############################################################################
ARG SCCACHE_VERSION=0.12.0
ARG SCCACHE_ARCHIVE=sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz
ENV SCCACHE_BUCKET_NAME=flagscale-build-sccache
ENV SCCACHE_REGION_NAME=cn-north-1
ENV SCCACHE_S3_NO_CREDENTIALS=0
RUN echo "Installing sccache..." && \
        curl -L -o sccache.tar.gz "https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/${SCCACHE_ARCHIVE}" && \
        tar -xzf sccache.tar.gz && \
        mv sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl/sccache /usr/bin/sccache && \
        rm -rf sccache.tar.gz sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl && \
        sccache --version

##############################################################################
# OPENMPI
##############################################################################
ENV OPENMPI_BASEVERSION=5.0
ENV OPENMPI_VERSION=${OPENMPI_BASEVERSION}.9
RUN wget -q -O - https://download.open-mpi.org/release/open-mpi/v${OPENMPI_BASEVERSION}/openmpi-${OPENMPI_VERSION}.tar.gz | tar xzf - && \
        cd openmpi-${OPENMPI_VERSION} && \
        ./configure --prefix=/usr/local/openmpi-${OPENMPI_VERSION} && \
        make -j"$(nproc)" install && \
        ln -s /usr/local/openmpi-${OPENMPI_VERSION} /usr/local/mpi && \
        # Sanity check:
        test -f /usr/local/mpi/bin/mpic++ && \
        cd .. && \
        rm -r openmpi-${OPENMPI_VERSION}
ENV PATH=/usr/local/mpi/bin:${PATH} \
        LD_LIBRARY_PATH=/usr/local/lib:/usr/local/mpi/lib:/usr/local/mpi/lib64:${LD_LIBRARY_PATH}
# Create a wrapper for OpenMPI to allow running as root by default
RUN mv /usr/local/mpi/bin/mpirun /usr/local/mpi/bin/mpirun.real && \
        echo '#!/bin/bash' > /usr/local/mpi/bin/mpirun && \
        echo 'mpirun.real --allow-run-as-root --prefix /usr/local/mpi "$@"' >> /usr/local/mpi/bin/mpirun && \
        chmod a+x /usr/local/mpi/bin/mpirun

##############################################################################
# Install Miniconda
##############################################################################
RUN mkdir -p ~/miniconda3 && \
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
        rm -rf ~/miniconda3/miniconda.sh && \
        ~/miniconda3/bin/conda init bash && \
        ~/miniconda3/bin/conda config --set auto_activate_base false && \
        ~/miniconda3/bin/conda config --set default_python ${PYTHON_VERSION}

##############################################################################
# Install cuDNN (NVIDIA CUDA Deep Neural Network library)
##############################################################################
ARG CUDNN_VERSION=9.15.1
RUN CUDNN_MAJOR=$(echo "${CUDNN_VERSION}" | cut -d. -f1) && \
        CUDNN_MINOR=$(echo "${CUDNN_VERSION}" | cut -d. -f2) && \
        CUDA_MAJOR=$(echo "${CUDA_VERSION}" | cut -d. -f1) && \
        CUDA_MINOR=$(echo "${CUDA_VERSION}" | cut -d. -f2) && \
        wget https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-x86_64/cudnn-linux-x86_64-${CUDNN_VERSION}.9_cuda${CUDA_MAJOR}-archive.tar.xz && \
        tar -xJvf cudnn-linux-x86_64-${CUDNN_VERSION}.9_cuda12-archive.tar.xz && \
        mkdir -p /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/include && \
        mkdir -p /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/lib64 && \
        cp cudnn-*-archive/include/cudnn*.h /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/include/ && \
        cp -P cudnn-*-archive/lib/libcudnn* /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/lib64/ && \
        chmod a+r /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/include/cudnn*.h /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/lib64/libcudnn* && \
        echo "export PATH=/usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/bin:\$PATH" >> ~/.bashrc && \
        echo "export LD_LIBRARY_PATH=/usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/lib64:\$LD_LIBRARY_PATH" >> ~/.bashrc && \
        cat /usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}/include/cudnn_version.h | grep CUDNN_MAJOR -A 2

##############################################################################
# Install uv for faster pip installs
##############################################################################
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install uv
# This timeout (in seconds) is necessary when installing some dependencies via uv since it's likely to time out
ENV UV_HTTP_TIMEOUT=500
# Dynamically adjust the concurrency based on the bandwidth limit (typical value is the number of CPU cores multiplied by 2)
ENV UV_CONCURRENCY=256
# Extend the waiting time for long connections to adapt to unstable network environments
ENV UV_CONNECT_TIMEOUT=60
# When the exact version is unavailable, automatically roll back to the semantically compatible highest available version
# ENV UV_INDEX_STRATEGY="unsafe-best-match"
# Use copy mode to avoid hardlink failures with Docker cache mounts
ENV UV_LINK_MODE=copy

##############################################################################
# FlagScale: Base Environment Installation Guide
##############################################################################
COPY requirements/requirements-base.txt requirements/requirements-base.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r ./requirements/requirements-base.txt

##############################################################################
# Set default shell
##############################################################################
SHELL ["/bin/bash", "-c"]

##############################################################################
# Clear
##############################################################################
RUN apt-get clean && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /root/.cache/* && \
        rm -rf /workspace/*
