defaults:
  - _self_
  - train: gr00t_n1_5

experiment:
  exp_name: gr00t_n1_5_train
  seed: 1000
  save_steps: 10000
  load: null
  exp_dir: outputs/${experiment.exp_name}
  ckpt_format: torch
  task:
    type: train
    backend: native
    entrypoint: flagscale/train/train_gr00t_n1_5.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    hostfile: null
  cmds:
    before_start: echo "Starting GR00T N1.5 Training"
  envs:
    LOGLEVEL: "INFO"
    CUDA_VISIBLE_DEVICES: "0,1,2,3,4,5,6,7"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    WANDB_MODE: offline
    OTEL_SDK_DISABLED: true

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
