# Remote host IP address for accessing log files
# remote_host: 192.0.2.1  # This IP address identifies the remote host where logs are stored
remote_host: ssh.platform.baai.ac.cn
# remote_host: 124.236.26.209

# Username for SSH login to the remote host
# remote_user: example_user  # This is the username used to log in to the remote host via SSH
remote_user: jd-yfb-dev.yefubao.flagscale_dev.cn-beijing-daxing.ws

# Port number used for SSH access
# remote_port: 22  # This is the standard SSH port used to connect to the remote host
remote_port: 22

# Path to the log file on the remote host
# remote_log_path: /path/example_log_file.log
remote_log_path: /root/monitorFile_test/host_7_job-0962e5a0-e294-4bc2-9fe0-72300dd55a81-worker-6.output

# Interval in seconds for checking the logs
# check_interval: 1200
check_interval: 20
