FROM flagscale:cuda12.8.1-cudnn9.7.1-python3.12-torch2.7.0-time250507031528 AS base
ARG CUDA_VERSION=12.8.1
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    echo "N" | apt-get install -y --no-install-recommends pkg-config && \
    apt-get install -y --no-install-recommends \
        autotools-dev \
        build-essential \
        ca-certificates ccache cmake curl \
        emacs \
        gcc git git-lfs g++ \
        htop \
        iftop iotop \
        libcairo2-dev libfontconfig-dev libibverbs1 libibverbs-dev libnuma-dev libx11-dev lsb-release \
        net-tools nfs-common ninja-build \
        openssh-server openssh-client \
        pdsh psmisc \
        rsync \
        screen software-properties-common sudo \
        tmux tzdata \
        unzip \
        vim \
        wget

######################################################
FROM nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu22.04 AS final
ARG WORK_DIR=/workspace
ARG STAGE_DIR=/tmp
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND noninteractive

COPY --from=base /etc /etc
COPY --from=base /usr/local /usr/local
COPY --from=base /usr/lib /usr/lib
COPY --from=base /usr/bin /usr/bin
COPY --from=base /usr/share /usr/share
COPY --from=base /usr/include /usr/include
COPY --from=base /var/cache/apt /var/cache/apt
COPY --from=base /var/lib/dpkg /var/lib/dpkg
COPY --from=base /var/lib/apt /var/lib/apt
COPY --from=base /root/.bashrc /root/.bashrc

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 && \
    update-alternatives --set python3 /usr/bin/python3.12 && \
    ln -sf /usr/bin/python3.12-config /usr/bin/python3-config && \
    ln -sf /usr/bin/python3 /usr/bin/python