# 基础镜像 flagscale:cuda12.8.1-cudnn9.7.1-python3.12-torch2.7.0-time2507111538 为创建好的完整镜像
FROM flagscale:cuda12.8.1-cudnn9.7.1-python3.12-torch2.7.0-time2507111538 AS base

# create inference
# 基础镜像（flagscale:cuda12.8.1-cudnn9.7.1-python3.12-torch2.7.0-base）为创建好的（仅包含conda base 环境）
FROM flagscale:cuda12.8.1-cudnn9.7.1-python3.12-torch2.7.0-base AS final
COPY --from=base /root/miniconda3/envs/flagscale-inference /root/miniconda3/envs/flagscale-inference