defaults:
  - _self_
  - train: qwen_gr00t

experiment:
  exp_name: qwen_gr00t_train
  seed: 42
  save_steps: 10000
  load: null
  exp_dir: outputs/${experiment.exp_name}
  ckpt_format: torch
  task:
    type: train
    backend: native
    entrypoint: flagscale/train/train_qwen_gr00t.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    hostfile: null
  cmds:
    before_start: echo "Starting Qwen-GR00T Training"
  envs:
    LOGLEVEL: "INFO"
    CUDA_VISIBLE_DEVICES: "0,1,2,3,4,5,6,7"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    WANDB_MODE: offline
    OTEL_SDK_DISABLED: true

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
