import os
import tempfile
from unittest.mock import patch

import pytest
from omegaconf import OmegaConf

from flagscale.runner.backend.backend_native_train import NativeTrainBackend


@pytest.fixture
def mock_config():
    """Create a mock config DictConfig for testing.

    Note: logging and checkpoint paths are normally generated by _update_config_train,
    but we set them here for test convenience since we mock that function.
    """
    config_dict = {
        "experiment": {
            "exp_dir": "/tmp/test_exp",
            "task": {
                "type": "train",
                "backend": "native_train",
                "entrypoint": "flagscale/train/train_pi.py",
            },
            "runner": {
                "hostfile": None,
                "no_shared_fs": False,
                "ssh_port": 22,
            },
            "envs": {
                "CUDA_VISIBLE_DEVICES": "0,1,2,3",
            },
            "cmds": {
                "before_start": "echo 'Starting'",
                "after_stop": "echo 'Stopping'",
            },
        },
        "train": {
            "system": {
                "checkpoint": {
                    "save": "/tmp/test_exp/checkpoints",
                    "load": "/tmp/test_exp/checkpoints",
                },
                "logging": {
                    "log_dir": "/tmp/test_exp/logs",
                    "scripts_dir": "/tmp/test_exp/logs/scripts",
                    "pids_dir": "/tmp/test_exp/logs/pids",
                    "details_dir": "/tmp/test_exp/logs/details",
                    "tensorboard_dir": "/tmp/test_exp/tensorboard",
                    "wandb_save_dir": "/tmp/test_exp/wandb",
                },
            },
        },
    }
    return OmegaConf.create(config_dict)


@pytest.fixture
def mock_get_args_native():
    """Mock _get_args_native function."""
    with patch("flagscale.runner.backend.backend_native_train._get_args_native") as mock:
        mock.return_value = ["--config-file=/tmp/test_config.yaml"]
        yield mock


@pytest.fixture
def mock_update_config_train():
    """Mock _update_config_train function."""
    with patch("flagscale.runner.backend.backend_native_train._update_config_train") as mock:
        yield mock


@pytest.fixture
def mock_parse_hostfile():
    """Mock parse_hostfile function."""
    with patch("flagscale.runner.backend.backend_native_train.parse_hostfile") as mock:
        mock.return_value = None
        yield mock


@pytest.fixture
def mock_logger():
    """Mock logger to avoid output during tests."""
    with patch("flagscale.runner.backend.backend_native_train.logger") as mock:
        yield mock


def test_backend_init_success(
    mock_config, mock_get_args_native, mock_update_config_train, mock_parse_hostfile, mock_logger
):
    """Test successful backend initialization."""
    backend = NativeTrainBackend(mock_config)

    assert backend.task_type == "train"
    assert backend.user_script == "flagscale/train/train_pi.py"
    assert backend.user_envs == {"CUDA_VISIBLE_DEVICES": "0,1,2,3"}
    assert backend.user_args == ["--config-file=/tmp/test_config.yaml"]
    assert backend.resources is None
    assert backend.device_type_specific is None
    assert backend.node_specific is None
    assert backend.rdzv_id is not None
    mock_update_config_train.assert_called_once_with(mock_config)
    mock_get_args_native.assert_called_once_with(mock_config)


def test_backend_init_wrong_task_type(mock_config, mock_get_args_native, mock_update_config_train):
    """Test backend initialization fails with wrong task type."""
    mock_config.experiment.task.type = "inference"

    with pytest.raises(AssertionError, match="Unsupported task type: inference"):
        NativeTrainBackend(mock_config)


def test_backend_prepare_with_hostfile(mock_config, mock_get_args_native, mock_update_config_train):
    """Test _prepare with hostfile."""
    mock_resources = {"host1": {"slots": 8, "type": "gpu"}}
    with patch("flagscale.runner.backend.backend_native_train.parse_hostfile") as mock_parse:
        mock_parse.return_value = mock_resources
        backend = NativeTrainBackend(mock_config)
        assert backend.resources == mock_resources


def test_backend_init_with_device_type_specific(
    mock_config, mock_get_args_native, mock_update_config_train, mock_parse_hostfile, mock_logger
):
    """Test backend initialization with device_type_specific config."""
    device_type_config = {
        "gpu": {"build_dir": "/custom/gpu/build"},
        "cpu": {"build_dir": "/custom/cpu/build"},
    }
    mock_config.device_type_specific = device_type_config

    backend = NativeTrainBackend(mock_config)

    assert backend.device_type_specific == device_type_config
    assert backend.device_type_specific["gpu"]["build_dir"] == "/custom/gpu/build"
    assert backend.device_type_specific["cpu"]["build_dir"] == "/custom/cpu/build"


def test_backend_init_with_node_specific(
    mock_config, mock_get_args_native, mock_update_config_train, mock_parse_hostfile, mock_logger
):
    """Test backend initialization with node_specific config."""
    node_config = {
        "host1": {"build_dir": "/custom/host1/build", "custom_arg": "value1"},
        "host2": {"build_dir": "/custom/host2/build", "custom_arg": "value2"},
    }
    mock_config.node_specific = node_config

    backend = NativeTrainBackend(mock_config)

    assert backend.node_specific == node_config
    assert backend.node_specific["host1"]["build_dir"] == "/custom/host1/build"
    assert backend.node_specific["host1"]["custom_arg"] == "value1"
    assert backend.node_specific["host2"]["build_dir"] == "/custom/host2/build"


def test_backend_init_with_both_specific_configs(
    mock_config, mock_get_args_native, mock_update_config_train, mock_parse_hostfile, mock_logger
):
    """Test backend initialization with both device_type_specific and node_specific."""
    device_type_config = {"gpu": {"build_dir": "/custom/gpu/build"}}
    node_config = {"host1": {"custom_arg": "value1"}}
    mock_config.device_type_specific = device_type_config
    mock_config.node_specific = node_config

    backend = NativeTrainBackend(mock_config)

    assert backend.device_type_specific == device_type_config
    assert backend.node_specific == node_config
    assert backend.device_type_specific["gpu"]["build_dir"] == "/custom/gpu/build"
    assert backend.node_specific["host1"]["custom_arg"] == "value1"


def test_generate_run_script_basic(mock_config, mock_get_args_native, mock_update_config_train):
    """Test generate_run_script creates correct script."""
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        # Update config to use temp directory
        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.log_dir = os.path.join(tmpdir, "logs")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        with (
            patch("os.path.exists", return_value=True),
            patch("os.path.abspath", return_value=tmpdir),
        ):
            script_path = backend.generate_run_script(
                mock_config, "localhost", 0, "test_cmd", background=True
            )

        assert os.path.exists(script_path)
        assert script_path.endswith("host_0_localhost_run.sh")

        # Read and verify script content
        with open(script_path, "r") as f:
            content = f.read()
            assert "#!/bin/bash" in content
            assert "echo 'Starting'" in content  # before_start command
            assert "test_cmd" in content
            assert "nohup" in content  # background mode
            assert "host_0_localhost.output" in content


def test_generate_run_script_no_shared_fs(
    mock_config, mock_get_args_native, mock_update_config_train
):
    """Test generate_run_script with no_shared_fs=True."""
    mock_config.experiment.runner.no_shared_fs = True
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.log_dir = os.path.join(tmpdir, "logs")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        with (
            patch("os.path.exists", return_value=True),
            patch("os.path.abspath", return_value=tmpdir),
        ):
            script_path = backend.generate_run_script(
                mock_config, "localhost", 0, "test_cmd", background=True
            )

        with open(script_path, "r") as f:
            content = f.read()
            assert "host.output" in content  # No node rank in filename


def test_generate_run_script_with_monitoring(
    mock_config, mock_get_args_native, mock_update_config_train
):
    """Test generate_run_script with monitoring enabled."""
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.log_dir = os.path.join(tmpdir, "logs")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        with (
            patch("os.path.exists", return_value=True),
            patch("os.path.abspath", return_value=tmpdir),
        ):
            script_path = backend.generate_run_script(
                mock_config, "localhost", 0, "test_cmd", background=True, enable_monitoring=True
            )

        with open(script_path, "r") as f:
            content = f.read()
            assert "monitor_launcher.py" in content
            assert "--log-dir" in content
            assert "--node-rank 0" in content
            assert "--enable-log-collection" in content


def test_generate_run_script_foreground(
    mock_config, mock_get_args_native, mock_update_config_train
):
    """Test generate_run_script with background=False uses tee for stdout + file."""
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.log_dir = os.path.join(tmpdir, "logs")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        with (
            patch("os.path.exists", return_value=True),
            patch("os.path.abspath", return_value=tmpdir),
        ):
            script_path = backend.generate_run_script(
                mock_config, "localhost", 0, "test_cmd", background=False
            )

        with open(script_path, "r") as f:
            content = f.read()
            assert "nohup" not in content
            assert "set -o pipefail" in content
            assert 'bash -c "$cmd; sync"' in content
            assert "tee -a" in content


def test_generate_stop_script(mock_config, mock_get_args_native, mock_update_config_train):
    """Test generate_stop_script creates correct script."""
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        script_path = backend.generate_stop_script("localhost", 0)

        assert os.path.exists(script_path)
        assert script_path.endswith("host_0_localhost_stop.sh")

        with open(script_path, "r") as f:
            content = f.read()
            assert "#!/bin/bash" in content
            assert "pkill -P $pid" in content
            assert "pkill -f 'torchrun'" in content
            assert "echo 'Stopping'" in content  # after_stop command


def test_generate_stop_script_no_after_stop(
    mock_config, mock_get_args_native, mock_update_config_train
):
    """Test generate_stop_script without after_stop command."""
    mock_config.experiment.cmds = None
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        script_path = backend.generate_stop_script("localhost", 0)

        with open(script_path, "r") as f:
            content = f.read()
            assert "echo 'Stopping'" not in content


def test_generate_run_script_custom_pkg_dir(
    mock_config, mock_get_args_native, mock_update_config_train
):
    """Test generate_run_script with custom pkg_dir."""
    backend = NativeTrainBackend(mock_config)

    with tempfile.TemporaryDirectory() as tmpdir:
        custom_root = os.path.join(tmpdir, "custom_root")
        os.makedirs(custom_root, exist_ok=True)

        mock_config.train.system.logging.scripts_dir = os.path.join(tmpdir, "scripts")
        mock_config.train.system.logging.log_dir = os.path.join(tmpdir, "logs")
        mock_config.train.system.logging.pids_dir = os.path.join(tmpdir, "pids")

        script_path = backend.generate_run_script(
            mock_config, "localhost", 0, "test_cmd", pkg_dir=custom_root
        )

        with open(script_path, "r") as f:
            content = f.read()
            assert f"cd {custom_root}" in content
