# .github/workflows/create-container-functional-tests.yml
name: Functional Tests

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      task:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  functional-test:
    runs-on: self-hosted
    container:
      image: ${{ inputs.image }}
      ports:
        - 80
      volumes:
        - /home/flagscale_cicd/flask/static:/workspace/report
        - /home/flagscale_cicd/docker/docker_build/docker_data:/home/gitlab-runner/data
        - /home/flagscale_cicd/docker/docker_build/docker_tokenizers:/home/gitlab-runner/tokenizers
      options: --gpus all --shm-size=500g --hostname flagscale_cicd --user root --ulimit nofile=65535:65535

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 负责将远程仓库的内容克隆到本地工作目录
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }} # 当前触发本次构建的那个 Pull Request 所对应的源仓库完整地址
          ref: ${{ github.event.pull_request.head.ref }} # 指定切换的 commit hash
          ssh-strict: true # 启用 SSH HostKey 校验机制
          ssh-user: git # 设定 SSH 用户名
          persist-credentials: true # 保留凭证信息供后续步骤复用
          clean: true # 先清空工作区再检出新内容，保证环境干净
          sparse-checkout-cone-mode: true # 只下载必要的部分而非整个仓库
          fetch-tags: false # 不获取标签信息，关闭它可以节省时间和资源
          show-progress: true # 显示进度条。让 CI 日志更直观地展示 clone/checkout 的过程进度，便于调试耗时问题
          lfs: false # 禁用 Git LFS
          submodules: false # 项目依赖外部子模块仓库使时，设为true
          set-safe-directory: true # 允许后续步骤在此目录下执行脚本而不会因权限问题被拦截

      - name: Run Functional Test
        run: |
          pip install gitpython # TODO: Remove after updating the image

          git config --global --add safe.directory /__w/FlagScale/FlagScale
          if [ "${{ inputs.type }}" = "train" ] || [ "${{ inputs.type }}" = "hetero_train" ]; then
            PYTHONPATH=./:$PYTHONPATH pip install . --config-settings=backend="Megatron-LM" --verbose --no-build-isolation
            if [ "${{ inputs.task }}" = "llava_onevision" ]; then
              PYTHONPATH=./:$PYTHONPATH pip install . --config-settings=backend="Megatron-Energon" --verbose --no-build-isolation
              cp -r third_party/Megatron-Energon/src/megatron/energon third_party/Megatron-LM/megatron
            fi
          elif [ "${{ inputs.type }}" = "inference" ] || [ "${{ inputs.type }}" = "serve" ] || [ "${{ inputs.type }}" = "inference-pipeline" ]; then
            source /root/miniconda3/bin/activate flagscale-inference
            pip install scikit-build scikit-build-core
            pip install --no-build-isolation git+https://github.com/FlagOpen/FlagGems.git@release_v1.0.0
            PYTHONPATH=./:$PYTHONPATH pip install . --config-settings=backend="vllm" --verbose --no-build-isolation
          elif [ "${{ inputs.type }}" = "rl" ]; then
            python tools/patch/unpatch.py --backend verl
            cd third_party/verl
            pip install --no-deps -e .
            cd ../..
          else
            echo "Unknown backend type: ${{ inputs.type }}"
            exit 1
          fi
          tests/scripts/functional_tests/test_task.sh --type ${{ inputs.type }} --task ${{ inputs.task }}
        shell: bash
